language: python
python: "3.5"

install:
      # Install deps
    - pip install numpy
      # Install seven
    - pip install -e .
      # Install test deps
    - pip install pytest pytest-cov coverage coveralls flake8

script:
    - set -e
    - flake8 --count seven
    - pytest -vl --cov=seven --cov-append

after_success:
    - codecov

notifications:
    email: false
