language: python
python: "3.5"

install:
      # Install deps
    - pip install 'numba>=0.51.2' 'joblib>=0.11' 'numpy>=1.14.0' 'scipy>=1.0.0' 'matplotlib>=2.1.2' 'nilearn>=0.5.2' 'scikit-learn>=0.22.1' 'threadpoolctl>=1.0.0' 'prox_tv'
      # Install hemolearn
    - pip install -e .
      # Install test deps
    - pip install pytest pytest-cov coverage codecov flake8

script:
    - set -e
    - flake8 --count hemolearn
    - pytest -vl --cov=hemolearn --cov-append

after_success:
    - codecov

notifications:
    email: false
